### ISSUE TITLE
Configs instead of constants?

### ISSUE THREAD

**Issue by hotmeteor** [appletonlearning/laravel-taxes#1]
Would it be better to have a large set of config files rather than embedding constants in every class?

Something like
```
/config
    -- US
        -- AK
        -- AL
        ...
```

**Comment by rmcdaniel** [comment]
@hotmeteor Interesting but I'm not sure these would really be configuration settings. The federal tax brackets and rates will be the same across all employers. The only exception is the state unemployment rate which can be different for different employers. But we do allow them to pass that in already. That might be a good candidate for a config.

**Comment by rmcdaniel** [comment]
@hotmeteor I originally made these into constants because that's how it was previously being done but I'm thinking it might make more sense to put them in the database. I'm brainstorming on the schema right now.

**Comment by rmcdaniel** [comment]
@hotmeteor After more thought, putting this stuff in the database doesn't make sense because it's not just the tax rates that can change but the actual formulas for calculating some or all of the taxes could change as well.

In reality, each tax shouldn't be thought of as an object+data but instead it should be thought of as an algorithm+data. That means we want to version the code too, not just the data, In other words, we want to version the entire class.

In order to achieve that, I have started using a strategy pattern. Each tax+date is a strategy and when we update the rates or formulas (typically yearly but not necessarily), we will create a new strategy based on that date.

This will allow us to calculate taxes for 2018 even though we are still in 2017 and vice versa.

For example, `FederalIncome` has a list of strategies like this:

```
const STRATEGIES = [
    '20170101',
];
```

And that specific strategy is stored in:

`Appleton\Taxes\Countries\US\FederalIncome\V20170101`

This gets resolved in the constructor based on the optional date you pass in. If you don't pass a date in then it defaults to `Carbon::now()`.
